### ISSUE TITLE
Can't resolve 'reshow-runtime/es/helpers/typeof'

### ISSUE THREAD

**Issue by Herteby** [react-atomic/react-atomic-organism#2]
I'm using smooth-scroll-to which has get-scroll-info as a dependency.
Suddenly my builds started failing. Turns out it was because the new version of this package relies on reshow-runtime, but doesn't include it as a dependency.

```
ERROR in ./node_modules/get-scroll-info/build/es/src/index.js
Module not found: Error: Can't resolve 'reshow-runtime/es/helpers/typeof'
```

**Comment by HillLiu** [comment]
Thanks for report.

I just think my base package already contain it.

It was fixed with version get-scroll-info@0.1.11
https://www.npmjs.com/package/get-scroll-info

changes. 
https://github.com/react-atomic/react-atomic-organism/commit/a5df7a39d1643766740e3399fe8a6a85c080aac9
