### ISSUE TITLE
How can I use only 'organism-react-video' my existing react app?

### ISSUE THREAD

**Issue by nasirzid** [react-atomic/react-atomic-organism#461]
How can I use only 'organism-react-video' my existing react app? Can I use this video player only basic youtube video controls? I don't want to show "watch later" , "share" these buttons in my youtube play.

**Comment by HillLiu** [comment]
@nasirzid 
There is a example. https://react-atomic-ui.js.org/#/Video

And you could check my changes.
https://github.com/react-atomic/react-atomic-ui/commit/f5a751f148ca20866d918070031231da7665c65d

When you enable controls and press stop will trigger more videos, it's Youtube's behavior.
