### ISSUE TITLE
Class-lib module entry and toggleClass default export

### ISSUE THREAD

**Issue by apo1798** [react-atomic/react-atomic-organism#580]
Hi Hill,

The `class-lib@0.0.13` module entry file seems to be mismatched with the path specified in the `package.json`. 
![256147873-9040ca3a-93c8-4574-952f-dd8789fef908](https://github.com/react-atomic/react-atomic-organism/assets/96214174/ba5f3b47-60d0-4425-9081-da5f6ca9b02b)

In addition, the toggleClass `export` seems to be missing in both `/es` and `/src` files.
![image](https://github.com/react-atomic/react-atomic-organism/assets/96214174/4a7f1991-d462-44ba-ad0c-336ebea51bf3)

Should you need any further information, feel free to let me know. Thank you in advance!

**Comment by HillLiu** [comment]
@apo1798 
You're correct, it's a bug in version 0.0.13.

You could try the latest version. 0.1.5

There is a quick example 
https://codesandbox.io/s/vibrant-snow-z3ssmc?file=/src/App.js

**Comment by apo1798** [comment]
Hi HIll,

Thanks for the quick response! I'm trying to move a project into Vite which uses ES Module to bundle. However, as the project heavily depends on other packages, upgrading to higher version will break the dependency. Please take a look at the following error message.

![image](https://github.com/react-atomic/react-atomic-organism/assets/96214174/8ee92027-c726-4496-90ec-5a8aca46774d)

Not sure whether it's possible to directly update the `class-lib@0.0.13` to fix two issues we're facing. If you have any ideas or solutions concerning the issues, feel free to share with us.

Thank you and looking forward to your ideas. ^_^

**Comment by HillLiu** [comment]
@apo1798,

Based on your screenshot, I highly recommend upgrading "reshow-const" and "get-safe-reg."

There are two reasons for this suggestion:

Both packages have zero dependencies, which means you are unlikely to encounter any new dependency issues.
It is essential to stay up-to-date with the latest versions, especially when dealing with daily high-security risks.
Should you encounter any new issues, please do not hesitate to let me know. I will make every effort to assist you in achieving your mission.

**Comment by apo1798** [comment]
Hi Hill,

Thanks for the response and suggestions! I've updated both packages to the latest version, and fortunately there's no errors. 

However, I've encountered other errors. 

1. There seems to be an incorrect import of the `reshow-worker@0.13.0-beta` package.

![image](https://github.com/react-atomic/react-atomic-organism/assets/96214174/65948d5c-bc57-4062-ba94-2fac060133fd)

After deleting the `worker-loader!`, the error disappear, like the following

![image](https://github.com/react-atomic/react-atomic-organism/assets/96214174/bd66a9d8-1d94-4ec9-930e-06a1d982b150)


The package `reshow-app@^0.13.0-beta` seems to be dependent on the `reshow-worker@0.13.0-beta` in the  `yarn.lock` file. Would you have any thoughts or suggestions concerning this?

---

2. Also, the browser console also shows an error `Not find a theme for name: [undefined]`.
![image](https://github.com/react-atomic/react-atomic-organism/assets/96214174/bb67366a-2bc7-42a7-87b3-b6f3ac75f997)

Not sure whether it's due to the migration from webpack to vite. The entry file for Vite (React) to hydrate is untouched as the following code:
```html
<!-- index.html -->
<body>
  <div id="app"></div>
  <script type="module" src="/src/client.js"></script>
</body>
```

```js
// /src/client.js
import client from 'reshow-app/client'
import app from '../ui/pages/index'

export default client(app)
```

The current workaround is to specify the `themePath` in the `<Reshow>` component. 
![code](https://github.com/react-atomic/react-atomic-organism/assets/96214174/cf61c450-eef2-4176-bdf1-68fa6ca84056)


Not sure this workaround is good enough. Feel free to share any thought or ask for more information. I'll be providing the requested materials soon.

Thank you again for reaching and helping me. Have a great Sunday night!

**Comment by HillLiu** [comment]
@apo1798 
For the first issue:
If web speed performance is not your primary concern, you could unplug reshow-worker. The reshow-worker is optional.

For the second issue:
I'm having difficulty understanding your use case. Could you please provide a minimal reproduction that will allow me to review it?

**Comment by apo1798** [comment]
Hi Hill,

I created [a minimal repo](https://github.com/apo1798/vite-migrate-test). The following are my steps to install modules and start the development server.

```shell
$ yarn install && yarn dev
```

Here, the terminal will show a error from `node_modules/reshow-worker/build/es/index.js:6:9:`. To temporarily solve the error, please revise the import path `'worker-loader!organism-react-ajax/build/es/src/worker'` into `'organism-react-ajax/build/es/src/worker'` of the '/node_modules/reshow-worker/build/es/index.js' file.

---

Open [the url of development port](http://localhost:5173) and toggle the devtools. There's an error message in the console.
> Not find a theme for name: [undefined] 

The current workaround is to specify the `themePath` of `Reshow` component. Uncomment line 74 of the 'ui/pages/index.jsx' file, and the browser should show a simple `Hello world` message. 

Feel free to share any ideas or thoughts concerning both the issues. Again thanks for spending time debugging with me. Have a great week ahead!

**Comment by apo1798** [comment]
Hi Hill,

After some investigations and discussions with my co-workers, I found the `worker-loader` is a feature belonging to Webpack 4. It might be hard for you to simply revise this as others might still be using Webpack 4 in their projects.

I later found a package called [patch-package](https://github.com/ds300/patch-package), which automatically revises the `worker-loader` after every installation. And now the import path can be recognized by Vite.

Thank you for all the supports and suggestions. Wishing you a great Sunday and success career.
